on:
  push:
    branches:
      - "*"
  # release:
  #   types: [created]

name: Upload to Dockerhub

jobs:
  deploy:
    name: Publish
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Install Elixir
      run: |
          brew update
          brew install elixir
          mix local.rebar --force
          mix local.hex --force

    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
          rust-version: stable

    - run: mix deps.get
    - run: mix test
    - run: MIX_ENV=prod mix release
      

    - name: Build Release
      uses: svenstaro/upload-release-action@v2
      with:
        name: hansonkd/crisscross
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}