on:
  push:
    branches:
      - "*"
  release:
    types: [created]

name: Upload to Dockerhub

jobs:
  deploy:
    name: Publish
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Cache Primes
      id: cache-brew
      uses: actions/cache@v2
      with:
        path: |
          ~/Library/Caches/Homebrew/*
          ~/Library/Caches/Homebrew/downloads/*
        key: ${{ runner.os }}-brew

    - name: Install Elixir
      if: steps.cache-brew.outputs.cache-hit != 'true'
      run: |
          brew update
          brew install elixir
          brew install zig
          brew install gzip
          brew install p7zip
          mix local.rebar --force
          mix local.hex --force

    - name: Setup | Rust
      uses: ATiltedTree/setup-rust@v1
      with:
          rust-version: stable

    - run: mix deps.get
    - run: MIX_ENV=prod mix release
      
    # - name: Build Release
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     name: hansonkd/crisscross
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: burrito_out/criss_cross_linux
    #     asset_name: crisscross_linux
    #     tag: ${{ github.ref }}

    # - name: Build Release
    #   uses: svenstaro/upload-release-action@v2
    #   with:
    #     name: hansonkd/crisscross
    #     repo_token: ${{ secrets.GITHUB_TOKEN }}
    #     file: burrito_out/criss_cross_macos
    #     asset_name: crisscross_macos
    #     tag: ${{ github.ref }}