on:
  push:
    branches:
      - "*"
  # release:
  #   types: [created]

name: Upload to Dockerhub

jobs:
  deploy:
    name: Publish
    runs-on: macos-11

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - uses: actions/setup-elixir@v1
      with:
          otp-version: '24'
          elixir-version: '1.12.3'
    
    - run: mix deps.get
    - run: mix test
    - run: MIX_ENV=prod mix release
      

    - name: Build Release
      uses: svenstaro/upload-release-action@v2
      with:
        name: hansonkd/crisscross
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}